import type { Metadata } from "next";
import '@/src/styles/globals.css';
import 'react-leaflet-cluster/dist/assets/MarkerCluster.css'
import 'react-leaflet-cluster/dist/assets/MarkerCluster.Default.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className="antialiased">
      <body className="h-screen flex flex-col bg-(--gray-eighty)" suppressHydrationWarning>
  <main className="flex-1 overflow-y-auto">
    {children}
  </main>
</body>
    </html>
  );
}