import type { Metadata } from "next";
import '@/src/styles/globals.css';
import 'react-leaflet-cluster/dist/assets/MarkerCluster.css'
import 'react-leaflet-cluster/dist/assets/MarkerCluster.Default.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen flex flex-col bg-(--gray-eighty)">
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}